use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{collect_tokens, escape_string, snake_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct CGenerator;

impl CodeGenerator for CGenerator {
    fn lang_name(&self) -> &str { "C" }
    fn file_extension(&self) -> &str { ".h" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("    ");
        let name = &pg.grammar.name;
        let guard = format!("{}_PARSER_H", name.to_uppercase());
        let tokens = collect_tokens(pg);

        w.line("/* Generated by pargen - do not edit manually */");
        w.blank();
        w.line(&format!("#ifndef {}", guard));
        w.line(&format!("#define {}", guard));
        w.blank();
        w.line("#include <stddef.h>");
        w.line("#include <stdlib.h>");
        w.line("#include <string.h>");
        w.line("#include <stdio.h>");
        w.line("#include <ctype.h>");
        w.blank();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_struct(&mut w, name);
        gen_node_struct(&mut w, name);
        gen_lexer_decl(&mut w, name);
        gen_parser_decl(&mut w, name);

        w.line(&format!("#endif /* {} */", guard));
        w.blank();

        gen_lexer_impl(&mut w, name, pg);
        gen_parser_impl(&mut w, name, pg);

        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("typedef enum {{", ));
    w.indent();
    for tok in tokens {
        w.line(&format!("{}_Token_{},", name, tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{}_Token_{},", name, implicit));
        }
    }
    w.line(&format!("{}_Token_EOF,", name));
    w.dedent();
    w.line(&format!("}} {}TokenKind;", name));
    w.blank();
}

fn gen_token_struct(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{}TokenKind kind;", name));
    w.line("char* text;");
    w.line("int line;");
    w.line("int col;");
    w.dedent();
    w.line(&format!("}} {}Token;", name));
    w.blank();
}

fn gen_node_struct(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("typedef struct {}Node {{", name));
    w.indent();
    w.line("char* kind;");
    w.line(&format!("struct {}Node** children;", name));
    w.line("int child_count;");
    w.line("int child_capacity;");
    w.line("char* text;");
    w.dedent();
    w.line(&format!("}} {}Node;", name));
    w.blank();
}

fn gen_lexer_decl(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line("const char* input;");
    w.line("int pos;");
    w.line("int line;");
    w.line("int col;");
    w.dedent();
    w.line(&format!("}} {}Lexer;", name));
    w.blank();

    w.line(&format!("{}Lexer {}_lexer_new(const char* input);", name, snake_case(name)));
    w.line(&format!("{}Token* {}_lexer_tokenize({}Lexer* lexer, int* out_count);", name, snake_case(name), name));
    w.blank();
}

fn gen_parser_decl(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{}Token* tokens;", name));
    w.line("int count;");
    w.line("int pos;");
    w.dedent();
    w.line(&format!("}} {}Parser;", name));
    w.blank();

    w.line(&format!("{}Parser {}_parser_new({}Token* tokens, int count);", name, snake_case(name), name));
    w.line(&format!("{}Node* {}_parser_parse({}Parser* parser);", name, snake_case(name), name));
    w.line(&format!("{}Node* {}_node_new(const char* kind);", name, snake_case(name)));
    w.line(&format!("void {}_node_add_child({}Node* parent, {}Node* child);", snake_case(name), name, name));
    w.line(&format!("void {}_node_free({}Node* node);", snake_case(name), name));
    w.blank();
}

fn gen_lexer_impl(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    let prefix = snake_case(name);

    w.line(&format!("/* === {} Lexer Implementation === */", name));
    w.blank();

    w.line(&format!("{}Lexer {}_lexer_new(const char* input) {{", name, prefix));
    w.indent();
    w.line(&format!("{}Lexer lexer = {{input, 0, 1, 1}};", name));
    w.line("return lexer;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("static void lexer_advance({prefix}Lexer* l) '{'");
    w.indent();
    w.line("if (l->pos < (int)strlen(l->input)) '{'");
    w.indent();
    w.line("if (l->input[l->pos] == '\\n') { l->line++; l->col = 1; }");
    w.line("else { l->col++; }");
    w.line("l->pos++;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("{}Token* {}_lexer_tokenize({}Lexer* lexer, int* out_count) {{", name, prefix, name));
    w.indent();
    w.line("int capacity = 64;");
    w.line(&format!("{}Token* tokens = malloc(sizeof({}Token) * capacity);", name, name));
    w.line("int count = 0;");
    w.line("int input_len = (int)strlen(lexer->input);");
    w.blank();
    w.line("while (lexer->pos < input_len) {");
    w.indent();
    w.line("char c = lexer->input[lexer->pos];");
    w.line("if (isspace(c)) { lexer_advance(lexer); continue; }");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let match_fn = format!("match_{}", snake_case(&rule.name));
        w.line(&format!("{{ {}Token tok = {}(lexer);", name, match_fn));
        w.line("if (tok.text != NULL) {");
        w.indent();
        if rule.is_skip() {
            w.line("free(tok.text); continue;");
        } else {
            w.line("if (count >= capacity) { capacity *= 2; tokens = realloc(tokens, sizeof(tokens[0]) * capacity); }");
            w.line("tokens[count++] = tok; continue;");
        }
        w.dedent();
        w.line("}}");
    }

    for implicit in &pg.implicit_tokens {
        let match_fn = format!("match_{}", snake_case(implicit));
        w.line(&format!("{{ {}Token tok = {}(lexer);", name, match_fn));
        w.line("if (tok.text != NULL) {");
        w.indent();
        w.line("if (count >= capacity) { capacity *= 2; tokens = realloc(tokens, sizeof(tokens[0]) * capacity); }");
        w.line("tokens[count++] = tok; continue;");
        w.dedent();
        w.line("}}");
    }

    w.line(&format!("fprintf(stderr, \"Unexpected character '%%c' at line %%d col %%d\\n\", c, lexer->line, lexer->col);"));
    w.line(&format!("free(tokens); return NULL;"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line("if (count >= capacity) { capacity++; tokens = realloc(tokens, sizeof(tokens[0]) * capacity); }");
    w.line(&format!("tokens[count].kind = {}_Token_EOF;", name));
    w.line("tokens[count].text = strdup(\"\");");
    w.line("tokens[count].line = lexer->line;");
    w.line("tokens[count].col = lexer->col;");
    w.line("count++;");
    w.blank();
    w.line("*out_count = count;");
    w.line("return tokens;");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let _prefix = snake_case(name);
    let match_fn = format!("match_{}", snake_case(&rule.name));

    w.line(&format!("static {}Token {}({}Lexer* lexer) {{", name, match_fn, name));
    w.indent();
    w.line("int saved_pos = lexer->pos;");
    w.line("int saved_line = lexer->line;");
    w.line("int saved_col = lexer->col;");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("const char* target = \"{}\";", escaped));
                w.line("int target_len = (int)strlen(target);");
                w.line("int input_len = (int)strlen(lexer->input);");
                w.line("for (int i = 0; i < target_len; i++) {");
                w.indent();
                w.line("if (lexer->pos + i >= input_len || lexer->input[lexer->pos + i] != target[i]) {");
                w.indent();
                w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
                w.dedent();
                w.line("}");
                w.dedent();
                w.line("}");
                w.line("char* text = malloc(target_len + 1);");
                w.line("strncpy(text, lexer->input + saved_pos, target_len);");
                w.line("text[target_len] = '\\0';");
                w.line("for (int i = 0; i < target_len; i++) { lexer_advance(lexer); }");
            }
            ElementKind::CharSet(_cs) => {
                w.line("int start = lexer->pos;");
                w.line("int input_len = (int)strlen(lexer->input);");
                w.line("while (lexer->pos < input_len && char_in_range(lexer->input[lexer->pos])) { lexer_advance(lexer); }");
                w.line("if (lexer->pos == start) {");
                w.indent();
                w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
                w.dedent();
                w.line("}");
                w.line("int len = lexer->pos - start;");
                w.line("char* text = malloc(len + 1);");
                w.line("strncpy(text, lexer->input + start, len);");
                w.line("text[len] = '\\0';");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("int start = lexer->pos;");
                                w.line("int input_len = (int)strlen(lexer->input);");
                                w.line("while (lexer->pos < input_len && char_in_range(lexer->input[lexer->pos])) { lexer_advance(lexer); }");
                                w.line("if (lexer->pos == start) {");
                                w.indent();
                                w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
                                w.dedent();
                                w.line("}");
                                w.line("int len = lexer->pos - start;");
                                w.line("char* text = malloc(len + 1);");
                                w.line("strncpy(text, lexer->input + start, len);");
                                w.line("text[len] = '\\0';");
                            }
                            _ => {
                                w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
                            }
                        }
                    }
                }
            }
            _ => {
                w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
            }
        }
    } else {
        w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
    }

    w.blank();
    if rule.is_skip() {
        w.line(&format!("return ({}Token){{{}_Token_EOF, text, saved_line, saved_col}};", name, name));
    } else {
        w.line(&format!("return ({}Token){{{name}_Token_{rule}, text, saved_line, saved_col}};", name, rule = rule.name));
    }
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let match_fn = format!("match_{}", snake_case(token_name));
    let lit = token_name_to_literal_c(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("static {}Token {}({}Lexer* lexer) {{", name, match_fn, name));
    w.indent();
    w.line("int saved_pos = lexer->pos;");
    w.line("int saved_line = lexer->line;");
    w.line("int saved_col = lexer->col;");
    w.line(&format!("const char* target = \"{}\";", escaped));
    w.line("int target_len = (int)strlen(target);");
    w.line("int input_len = (int)strlen(lexer->input);");
    w.line("for (int i = 0; i < target_len; i++) {");
    w.indent();
    w.line("if (lexer->pos + i >= input_len || lexer->input[lexer->pos + i] != target[i]) {");
    w.indent();
    w.line(&format!("{}Token none = {{{}_Token_EOF, NULL, 0, 0}}; return none;", name, name));
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.line("char* text = malloc(target_len + 1);");
    w.line("strncpy(text, lexer->input + saved_pos, target_len);");
    w.line("text[target_len] = '\\0';");
    w.line("for (int i = 0; i < target_len; i++) { lexer_advance(lexer); }");
    w.line(&format!("return ({name}Token){{{name}_Token_{token}, text, saved_line, saved_col}};", name = name, token = token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal_c(name: &str) -> String {
    let mut result = String::new();
    for c in name.chars() {
        result.push(c.to_ascii_lowercase());
    }
    result
}

fn gen_parser_impl(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    let prefix = snake_case(name);

    w.line(&format!("/* === {} Parser Implementation === */", name));
    w.blank();

    w.line(&format!("{}Node* {}_node_new(const char* kind) {{", name, prefix));
    w.indent();
    w.line(&format!("{}Node* node = malloc(sizeof({}Node));", name, name));
    w.line("node->kind = strdup(kind);");
    w.line("node->children = NULL;");
    w.line("node->child_count = 0;");
    w.line("node->child_capacity = 0;");
    w.line("node->text = NULL;");
    w.line("return node;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("void {}_node_add_child({}Node* parent, {}Node* child) {{", prefix, name, name));
    w.indent();
    w.line("if (parent->child_count >= parent->child_capacity) {");
    w.indent();
    w.line("parent->child_capacity = parent->child_capacity == 0 ? 4 : parent->child_capacity * 2;");
    w.line(&format!("parent->children = realloc(parent->children, sizeof({}Node*) * parent->child_capacity);", name));
    w.dedent();
    w.line("}");
    w.line("parent->children[parent->child_count++] = child;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("{}Parser {}_parser_new({}Token* tokens, int count) {{", name, prefix, name));
    w.indent();
    w.line(&format!("{}Parser parser = {{tokens, count, 0}};", name));
    w.line("return parser;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("static {}Token* parser_current({}Parser* p) {{", name, name));
    w.indent();
    w.line("if (p->pos < p->count) return &p->tokens[p->pos];");
    w.line("return &p->tokens[p->count - 1];");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("static {}Token* parser_match({}Parser* p, {}TokenKind kind) {{", name, name, name));
    w.indent();
    w.line("if (parser_current(p)->kind == kind) { return &p->tokens[p->pos++]; }");
    w.line("return NULL;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("static {}Token* parser_expect({}Parser* p, {}TokenKind kind) {{", name, name, name));
    w.indent();
    w.line(&format!("{}Token* tok = parser_match(p, kind);", name));
    w.line("if (tok) return tok;");
    w.line(&format!("{}Token* cur = parser_current(p);", name));
    w.line(&format!("fprintf(stderr, \"Unexpected token at line %%d col %%d\\n\", cur->line, cur->col);"));
    w.line("exit(1);");
    w.line("return NULL;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("{}Node* {}_parser_parse({}Parser* parser) {{", name, prefix, name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return parse_{}(parser);", snake_case(&first.name)));
    } else {
        w.line("fprintf(stderr, \"No parser rules\\n\"); exit(1); return NULL;");
    }
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }

    w.line(&format!("void {}_node_free({}Node* node) {{", prefix, name));
    w.indent();
    w.line("if (!node) return;");
    w.line("for (int i = 0; i < node->child_count; i++) {");
    w.indent();
    w.line(&format!("{}_node_free(node->children[i]);", prefix));
    w.dedent();
    w.line("}");
    w.line("free(node->children);");
    w.line("free(node->kind);");
    w.line("if (node->text) free(node->text);");
    w.line("free(node);");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("static int char_in_range(char c) { return 0; /* implement based on grammar */ }");
    w.blank();
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("parse_{}", snake_case(&rule.name));
    w.line(&format!("static {}Node* {}({}Parser* p) {{", name, fn_name, name));
    w.indent();
    w.line(&format!("{}Node* node = {}_node_new(\"{}\");", name, snake_case(name), rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node;");
    } else {
        w.line(&format!("switch (parser_current(p)->kind) {{"));
        w.indent();
        for alt in &rule.alternatives {
            let first_elem = alt.elements.first();
            let match_arm = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("case {}_Token_{}:", name, tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("case {}_Token_{}:", name, tok_name)
                    }
                    _ => "default:".to_string(),
                }
            } else {
                "default:".to_string()
            };
            w.line(&match_arm);
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node;");
            w.dedent();
        }
        w.line("default:");
        w.indent();
        w.line("fprintf(stderr, \"Unexpected token\\n\"); exit(1); return NULL;");
        w.dedent();
        w.dedent();
        w.line("}");
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    let prefix = snake_case(name);
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("{{ {}Token* t = parser_expect(p, {}_Token_{});", name, name, tok));
                w.line(&format!("  {}Node* tn = {}_node_new(\"Token\"); tn->text = strdup(t->text); {}_node_add_child(node, tn); }}", name, prefix, prefix));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("{{ {}Token* t = parser_expect(p, {}_Token_{});", name, name, tok_name));
                w.line(&format!("  {}Node* tn = {}_node_new(\"Token\"); tn->text = strdup(t->text); {}_node_add_child(node, tn); }}", name, prefix, prefix));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("{}_node_add_child(node, parse_{}(p));", prefix, snake_case(r)));
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("while (1) {");
                w.indent();
                w.line("int saved = p->pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (p->pos == saved) break;");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("while (1) {");
                w.indent();
                w.line("int saved = p->pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (p->pos == saved) break;");
                w.dedent();
                w.line("}");
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("int saved = p->pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (0) {} /* placeholder for backtracking */");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}
