use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{collect_tokens, escape_string, pascal_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct CppGenerator;

impl CodeGenerator for CppGenerator {
    fn lang_name(&self) -> &str { "C++" }
    fn file_extension(&self) -> &str { ".hpp" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("    ");
        let name = &pg.grammar.name;
        let guard = format!("{}_PARSER_HPP", name.to_uppercase());
        let tokens = collect_tokens(pg);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();
        w.line(&format!("#ifndef {}", guard));
        w.line(&format!("#define {}", guard));
        w.blank();
        w.line("#include <string>");
        w.line("#include <vector>");
        w.line("#include <memory>");
        w.line("#include <stdexcept>");
        w.line("#include <optional>");
        w.line("#include <sstream>");
        w.blank();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_struct(&mut w, name);
        gen_lexer_class(&mut w, name, pg);
        gen_node_class(&mut w, name, pg);
        gen_parser_class(&mut w, name, pg);

        w.line(&format!("#endif /* {} */", guard));
        w.blank();

        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("enum class {}TokenKind {{", name));
    w.indent();
    for tok in tokens {
        w.line(&format!("{},", tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{},", implicit));
        }
    }
    w.line("Eof,");
    w.dedent();
    w.line("};");
    w.blank();
}

fn gen_token_struct(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("struct {}Token {{", name));
    w.indent();
    w.line(&format!("{}TokenKind kind;", name));
    w.line("std::string text;");
    w.line("int line = 0;");
    w.line("int col = 0;");
    w.dedent();
    w.line("};");
    w.blank();
}

fn gen_lexer_class(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("class {}Lexer {{", name));
    w.indent();
    w.line("public:");
    w.indent();
    w.line(&format!("explicit {}Lexer(const std::string& input) : input_(input), pos_(0), line_(1), col_(1) {{}}", name));
    w.blank();

    w.line(&format!("std::vector<{}Token> tokenize() {{", name));
    w.indent();
    w.line(&format!("std::vector<{}Token> tokens;", name));
    w.line("while (pos_ < input_.size()) {");
    w.indent();
    w.line("char c = input_[pos_];");
    w.line("if (std::isspace(static_cast<unsigned char>(c))) { advance(); continue; }");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let method = format!("tryMatch{}", pascal_case(&rule.name));
        w.line(&format!("if (auto tok = {}()) {{", method));
        w.indent();
        if rule.is_skip() {
            w.line("continue;");
        } else {
            w.line("tokens.push_back(*tok); continue;");
        }
        w.dedent();
        w.line("}");
    }

    for implicit in &pg.implicit_tokens {
        let method = format!("tryMatch{}", implicit);
        w.line(&format!("if (auto tok = {}()) {{", method));
        w.indent();
        w.line("tokens.push_back(*tok); continue;");
        w.dedent();
        w.line("}");
    }

    w.line(&format!("throw std::runtime_error(\"Unexpected character at line \" + std::to_string(line_) + \" col \" + std::to_string(col_));"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokens.push_back({}Token{{{name}TokenKind::Eof, \"\", line_, col_}});", name, name = name));
    w.line("return tokens;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.blank();

    w.line("private:");
    w.indent();
    w.line("std::string input_;");
    w.line("size_t pos_;");
    w.line("int line_;");
    w.line("int col_;");
    w.blank();

    w.line("void advance() {");
    w.indent();
    w.line("if (pos_ < input_.size()) {");
    w.indent();
    w.line("if (input_[pos_] == '\\n') { line_++; col_ = 1; }");
    w.line("else { col_++; }");
    w.line("pos_++;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("char peek(size_t offset = 0) const {");
    w.indent();
    w.line("return (pos_ + offset < input_.size()) ? input_[pos_ + offset] : '\\0';");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }

    w.dedent();
    w.line("};");
    w.blank();
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let method = format!("tryMatch{}", pascal_case(&rule.name));
    w.line(&format!("std::optional<{}Token> {}() {{", name, method));
    w.indent();
    w.line("size_t saved_pos = pos_;");
    w.line("int saved_line = line_;");
    w.line("int saved_col = col_;");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("const std::string target = \"{}\";", escaped));
                w.line("for (size_t i = 0; i < target.size(); i++) {");
                w.indent();
                w.line("if (peek(i) != target[i]) { pos_ = saved_pos; return std::nullopt; }");
                w.dedent();
                w.line("}");
                w.line("std::string text = input_.substr(saved_pos, target.size());");
                w.line("for (size_t i = 0; i < target.size(); i++) { advance(); }");
            }
            ElementKind::CharSet(_cs) => {
                w.line("size_t start = pos_;");
                w.line("while (pos_ < input_.size() && charInRange(input_[pos_])) { advance(); }");
                w.line("if (pos_ == start) { return std::nullopt; }");
                w.line("std::string text = input_.substr(start, pos_ - start);");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("size_t start = pos_;");
                                w.line("while (pos_ < input_.size() && charInRange(input_[pos_])) { advance(); }");
                                w.line("if (pos_ == start) { return std::nullopt; }");
                                w.line("std::string text = input_.substr(start, pos_ - start);");
                            }
                            _ => {
                                w.line("std::string text;");
                            }
                        }
                    }
                }
            }
            _ => {
                w.line("std::string text;");
            }
        }
    } else {
        w.line("std::string text;");
    }

    w.blank();
    if rule.is_skip() {
        w.line("return std::nullopt;");
    } else {
        w.line(&format!("return {}Token{{{name}TokenKind::{rule}, text, saved_line, saved_col}};", name, name = name, rule = rule.name));
    }
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let method = format!("tryMatch{}", token_name);
    let lit = token_name_to_literal_cpp(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("std::optional<{}Token> {}() {{", name, method));
    w.indent();
    w.line("size_t saved_pos = pos_;");
    w.line("int saved_line = line_;");
    w.line("int saved_col = col_;");
    w.line(&format!("const std::string target = \"{}\";", escaped));
    w.line("for (size_t i = 0; i < target.size(); i++) {");
    w.indent();
    w.line("if (peek(i) != target[i]) { pos_ = saved_pos; return std::nullopt; }");
    w.dedent();
    w.line("}");
    w.line("std::string text = input_.substr(saved_pos, target.size());");
    w.line("for (size_t i = 0; i < target.size(); i++) { advance(); }");
    w.line(&format!("return {}Token{{{name}TokenKind::{token}, text, saved_line, saved_col}};", name, name = name, token = token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal_cpp(name: &str) -> String {
    let mut result = String::new();
    for c in name.chars() {
        result.push(c.to_ascii_lowercase());
    }
    result
}

fn gen_node_class(w: &mut super::CodeWriter, name: &str, _pg: &ProcessedGrammar) {
    w.line(&format!("struct {}Node {{", name));
    w.indent();
    w.line("std::string kind;");
    w.line(&format!("std::vector<std::shared_ptr<{}Node>> children;", name));
    w.line("std::optional<std::string> text;");
    w.line(&format!("std::optional<{}TokenKind> token_kind;", name));
    w.blank();
    w.line(&format!("explicit {}Node(const std::string& k) : kind(k) {{}}", name));
    w.blank();

    w.line(&format!("void add_child(std::shared_ptr<{}Node> child) {{", name));
    w.indent();
    w.line("children.push_back(std::move(child));");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("std::string to_string(int indent = 0) const {");
    w.indent();
    w.line("std::ostringstream ss;");
    w.line("ss << std::string(indent, ' ') << kind;");
    w.line("if (text) ss << \": '\" << *text << \"'\";");
    w.line("ss << '\\n';");
    w.line("for (auto& child : children) ss << child->to_string(indent + 2);");
    w.line("return ss.str();");
    w.dedent();
    w.line("}");

    w.dedent();
    w.line("};");
    w.blank();
}

fn gen_parser_class(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("class {}Parser {{", name));
    w.indent();
    w.line("public:");
    w.indent();
    w.line(&format!("explicit {}Parser(const std::vector<{}Token>& tokens) : tokens_(tokens), pos_(0) {{}}", name, name));
    w.blank();

    w.line(&format!("std::shared_ptr<{}Node> parse() {{", name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return parse{}();", pascal_case(&first.name)));
    } else {
        w.line("throw std::runtime_error(\"No parser rules defined\");");
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.blank();

    w.line("private:");
    w.indent();
    w.line(&format!("std::vector<{}Token> tokens_;", name));
    w.line("size_t pos_;");
    w.blank();

    w.line(&format!("const {}Token& current() const {{", name));
    w.indent();
    w.line("return pos_ < tokens_.size() ? tokens_[pos_] : tokens_.back();");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("const {}Token* match({}TokenKind kind) {{", name, name));
    w.indent();
    w.line("if (current().kind == kind) { return &tokens_[pos_++]; }");
    w.line("return nullptr;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("const {}Token& expect({}TokenKind kind) {{", name, name));
    w.indent();
    w.line("if (auto* tok = match(kind)) { return *tok; }");
    w.line("auto& cur = current();");
    w.line("throw std::runtime_error(\"Unexpected token at line \" + std::to_string(cur.line));");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }

    w.dedent();
    w.line("};");
    w.blank();

    w.line("inline bool charInRange(char c) { return false; /* implement based on grammar */ }");
    w.blank();
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let method = format!("parse{}", pascal_case(&rule.name));
    w.line(&format!("std::shared_ptr<{}Node> {}() {{", name, method));
    w.indent();
    w.line(&format!("auto node = std::make_shared<{}Node>(\"{}\");", name, rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node;");
    } else {
        w.line(&format!("switch (current().kind) {{"));
        w.indent();
        for alt in &rule.alternatives {
            let first_elem = alt.elements.first();
            let match_arm = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("case {}TokenKind::{}:", name, tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("case {}TokenKind::{}:", name, tok_name)
                    }
                    _ => "default:".to_string(),
                }
            } else {
                "default:".to_string()
            };
            w.line(&match_arm);
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node;");
            w.dedent();
        }
        w.line("default:");
        w.indent();
        w.line("throw std::runtime_error(\"Unexpected token\");");
        w.dedent();
        w.dedent();
        w.line("}");
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("{{ auto& t = expect({}TokenKind::{});", name, tok));
                w.line(&format!("  auto tn = std::make_shared<{}Node>(\"Token\"); tn->text = t.text; node->add_child(tn); }}", name));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("{{ auto& t = expect({}TokenKind::{});", name, tok_name));
                w.line(&format!("  auto tn = std::make_shared<{}Node>(\"Token\"); tn->text = t.text; node->add_child(tn); }}", name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("node->add_child(parse{}());", pascal_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("size_t saved = pos_;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (...) { pos_ = saved; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("while (true) {");
                w.indent();
                w.line("size_t saved = pos_;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (...) { pos_ = saved; break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("while (true) {");
                w.indent();
                w.line("size_t saved = pos_;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (...) { pos_ = saved; break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}
