use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{collect_tokens, escape_string, pascal_case, snake_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct GoGenerator;

impl CodeGenerator for GoGenerator {
    fn lang_name(&self) -> &str { "Go" }
    fn file_extension(&self) -> &str { ".go" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("\t");
        let name = &pg.grammar.name;
        let pkg = snake_case(name);
        let tokens = collect_tokens(pg);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();
        w.line(&format!("package {}", pkg));
        w.blank();
        w.line("import (");
        w.indent();
        w.line("\"fmt\"");
        w.line("\"strings\"");
        w.dedent();
        w.line(")");
        w.blank();

        gen_token_type(&mut w, name, &tokens, pg);
        gen_token_struct(&mut w, name);
        gen_lexer(&mut w, name, pg);
        gen_node(&mut w, name, pg);
        gen_parser(&mut w, name, pg);
        gen_errors(&mut w, name);

        w.to_string()
    }
}

fn gen_token_type(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("type {}TokenKind int", name));
    w.blank();
    w.line("const (");
    w.indent();
    w.line(&format!("{}TokenEOF {}TokenKind = iota", name, name));
    for tok in tokens {
        w.line(&format!("Token{}", tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("Token{}", implicit));
        }
    }
    w.dedent();
    w.line(")");
    w.blank();

    w.line(&format!("func (k {}TokenKind) String() string {{", name));
    w.indent();
    w.line("switch k {");
    w.indent();
    w.line(&format!("case {}TokenEOF: return \"EOF\"", name));
    for tok in tokens {
        w.line(&format!("case Token{}: return \"{}\"", tok, tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("case Token{}: return \"{}\"", implicit, implicit));
        }
    }
    w.dedent();
    w.line("}");
    w.line("return fmt.Sprintf(\"Unknown(%d)\", int(k))");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_token_struct(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("type {}Token struct {{", name));
    w.indent();
    w.line(&format!("Kind {}TokenKind", name));
    w.line("Text string");
    w.line("Line int");
    w.line("Col  int");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("type {}Lexer struct {{", name));
    w.indent();
    w.line("input []rune");
    w.line("pos   int");
    w.line("line  int");
    w.line("col   int");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func New{}Lexer(input string) *{}Lexer {{", name, name));
    w.indent();
    w.line(&format!("return &{}Lexer{{input: []rune(input), pos: 0, line: 1, col: 1}}", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (l *{}Lexer) Tokenize() ([]{}Token, error) {{", name, name));
    w.indent();
    w.line(&format!("var tokens []{}Token", name));
    w.line("for l.pos < len(l.input) {");
    w.indent();
    w.line("c := l.input[l.pos]");
    w.line("if c == ' ' || c == '\\t' || c == '\\n' || c == '\\r' {");
    w.indent();
    w.line("l.advance()");
    w.line("continue");
    w.dedent();
    w.line("}");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        w.line(&format!("if tok, ok := l.tryMatch{}(); ok {{", pascal_case(&rule.name)));
        w.indent();
        if rule.is_skip() {
        } else {
            w.line("tokens = append(tokens, tok)");
        }
        w.line("continue");
        w.dedent();
        w.line("}");
    }

    for implicit in &pg.implicit_tokens {
        w.line(&format!("if tok, ok := l.tryMatch{}(); ok {{", implicit));
        w.indent();
        w.line("tokens = append(tokens, tok)");
        w.line("continue");
        w.dedent();
        w.line("}");
    }

    w.line(&format!("return nil, fmt.Errorf(\"unexpected character %c at line %d col %d\", c, l.line, l.col)"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokens = append(tokens, {}Token{{Kind: {}TokenEOF, Text: \"\", Line: l.line, Col: l.col}})", name, name));
    w.line("return tokens, nil");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (l *{}Lexer) advance() {{", name));
    w.indent();
    w.line("if l.pos < len(l.input) {");
    w.indent();
    w.line("if l.input[l.pos] == '\\n' { l.line++; l.col = 1 } else { l.col++ }");
    w.line("l.pos++");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (l *{}Lexer) peek() (rune, bool) {{", name));
    w.indent();
    w.line("if l.pos < len(l.input) { return l.input[l.pos], true }");
    w.line("return 0, false");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("tryMatch{}", pascal_case(&rule.name));
    w.line(&format!("func (l *{}Lexer) {}() ({}Token, bool) {{", name, fn_name, name));
    w.indent();
    w.line("savedPos := l.pos");
    w.line("savedLine := l.line");
    w.line("savedCol := l.col");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("target := \"{}\"", escaped));
                w.line("for i, c := range target {");
                w.indent();
                w.line(&format!("if l.pos + i >= len(l.input) || l.input[l.pos + i] != c {{ return {}Token{{}}, false }}", name));
                w.dedent();
                w.line("}");
                w.line("text := string(l.input[l.pos:l.pos+len(target)])");
                w.line("for _ = range target { l.advance() }");
            }
            ElementKind::CharSet(_cs) => {
                w.line("start := l.pos");
                w.line("for l.pos < len(l.input) {");
                w.indent();
                w.line("c := l.input[l.pos]");
                w.line("if !charInRanges(c) { break }");
                w.line("l.advance()");
                w.dedent();
                w.line("}");
                w.line(&format!("if l.pos == start {{ return {}Token{{}}, false }}", name));
                w.line("text := string(l.input[start:l.pos])");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("start := l.pos");
                                w.line("for l.pos < len(l.input) {");
                                w.indent();
                                w.line("c := l.input[l.pos]");
                                w.line("if !charInRanges(c) { break }");
                                w.line("l.advance()");
                                w.dedent();
                                w.line("}");
                                w.line(&format!("if l.pos == start {{ return {}Token{{}}, false }}", name));
                                w.line("text := string(l.input[start:l.pos])");
                            }
                            _ => {
                                w.line("text := \"\"");
                            }
                        }
                    }
                }
            }
            _ => {
                w.line("text := string(l.input[savedPos:l.pos])");
            }
        }
    } else {
        w.line("text := string(l.input[savedPos:l.pos])");
    }

    w.blank();
    if rule.is_skip() {
        w.line(&format!("return {}Token{{}}, true", name));
    } else {
        w.line(&format!("return {}Token{{Kind: Token{}, Text: text, Line: savedLine, Col: savedCol}}, true", name, rule.name));
    }
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let fn_name = format!("tryMatch{}", token_name);
    let lit = token_name_to_literal_go(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("func (l *{}Lexer) {}() ({}Token, bool) {{", name, fn_name, name));
    w.indent();
    w.line("savedPos := l.pos");
    w.line("savedLine := l.line");
    w.line("savedCol := l.col");
    w.line(&format!("target := \"{}\"", escaped));
    w.line("for i, c := range target {");
    w.indent();
    w.line(&format!("if l.pos + i >= len(l.input) || l.input[l.pos + i] != c {{ return {}Token{{}}, false }}", name));
    w.dedent();
    w.line("}");
    w.line("text := string(l.input[l.pos:l.pos+len(target)])");
    w.line("for _ = range target { l.advance() }");
    w.line(&format!("return {}Token{{Kind: Token{}, Text: text, Line: savedLine, Col: savedCol}}, true", name, token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal_go(name: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = name.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if i > 0 && chars[i].is_ascii_uppercase() {
            let next_lower = if i + 1 < chars.len() && chars[i + 1].is_ascii_lowercase() {
                true
            } else {
                false
            };
            if next_lower || i + 1 >= chars.len() {
                result.push(chars[i].to_ascii_lowercase());
            } else {
                result.push(chars[i].to_ascii_lowercase());
            }
        } else {
            result.push(chars[i].to_ascii_lowercase());
        }
        i += 1;
    }
    result
}

fn gen_node(w: &mut super::CodeWriter, name: &str, _pg: &ProcessedGrammar) {
    w.line(&format!("type {}Node struct {{", name));
    w.indent();
    w.line("Kind     string");
    w.line(&format!("Children []*{}Node", name));
    w.line(&format!("Token    *{}Token", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func New{}Node(kind string) *{}Node {{", name, name));
    w.indent();
    w.line(&format!("return &{}Node{{Kind: kind, Children: []*{}Node{{}}}}", name, name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func NewTokenNode(tok {}Token) *{}Node {{", name, name));
    w.indent();
    w.line(&format!("return &{}Node{{Kind: \"Token\", Token: &tok, Children: []*{}Node{{}}}}", name, name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (n *{}Node) AddChild(child *{}Node) {{", name, name));
    w.indent();
    w.line("n.Children = append(n.Children, child)");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("type {}Parser struct {{", name));
    w.indent();
    w.line(&format!("tokens []{}Token", name));
    w.line("pos    int");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func New{}Parser(tokens []{}Token) *{}Parser {{", name, name, name));
    w.indent();
    w.line(&format!("return &{}Parser{{tokens: tokens, pos: 0}}", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (p *{}Parser) Parse() (*{}Node, error) {{", name, name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return p.parse{}()", pascal_case(&first.name)));
    } else {
        w.line("return nil, fmt.Errorf(\"no parser rules defined\")");
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (p *{}Parser) current() {}Token {{", name, name));
    w.indent();
    w.line("if p.pos < len(p.tokens) { return p.tokens[p.pos] }");
    w.line("return p.tokens[len(p.tokens)-1]");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (p *{}Parser) matchToken(kind {}TokenKind) ({}Token, bool) {{", name, name, name));
    w.indent();
    w.line("if p.current().Kind == kind {");
    w.indent();
    w.line("tok := p.tokens[p.pos]");
    w.line("p.pos++");
    w.line("return tok, true");
    w.dedent();
    w.line("}");
    w.line(&format!("return {}Token{{}}, false", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("func (p *{}Parser) expect(kind {}TokenKind) ({}Token, error) {{", name, name, name));
    w.indent();
    w.line("if tok, ok := p.matchToken(kind); ok {");
    w.indent();
    w.line("return tok, nil");
    w.dedent();
    w.line("}");
    w.line("cur := p.current()");
    w.line(&format!("return {}Token{{}}, fmt.Errorf(\"unexpected token %v ('%s') at line %d col %d\", cur.Kind, cur.Text, cur.Line, cur.Col)", name));
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("parse{}", pascal_case(&rule.name));
    w.line(&format!("func (p *{}Parser) {}() (*{}Node, error) {{", name, fn_name, name));
    w.indent();
    w.line(&format!("node := New{}Node(\"{}\")", name, rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node, nil");
    } else {
        w.line("switch p.current().Kind {");
        w.indent();
        for (i, alt) in rule.alternatives.iter().enumerate() {
            let first_elem = alt.elements.first();
            let match_arm = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("Token{}:", tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("Token{}:", tok_name)
                    }
                    _ => "default:".to_string(),
                }
            } else {
                "default:".to_string()
            };

            if i == rule.alternatives.len() - 1 && match_arm != "default:" {
                w.line("default:");
            } else {
                w.line(&match_arm);
            }
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node, nil");
            w.dedent();
        }
        if !rule.alternatives.iter().any(|a| a.elements.is_empty()) {
            w.line("default:");
            w.indent();
            w.line("cur := p.current()");
            w.line(&format!("return nil, fmt.Errorf(\"unexpected token %v at line %d\", cur.Kind, cur.Line)"));
            w.dedent();
        }
        w.dedent();
        w.line("}");
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("if tok, err := p.expect(Token{}); err != nil {{ return nil, err }} else {{ node.AddChild(NewTokenNode(tok)) }}", tok));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("if tok, err := p.expect(Token{}); err != nil {{ return nil, err }} else {{ node.AddChild(NewTokenNode(tok)) }}", tok_name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("if child, err := p.parse{}(); err != nil {{ return nil, err }} else {{ node.AddChild(child) }}", pascal_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("saved := p.pos");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("_ = saved");
                w.dedent();
                w.line("}");
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("for {");
                w.indent();
                w.line("saved := p.pos");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if p.pos == saved { break }");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("for {");
                w.indent();
                w.line("saved := p.pos");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if p.pos == saved { break }");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}

fn gen_errors(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("type {}LexError struct {{", name));
    w.indent();
    w.line("Msg  string");
    w.line("Line int");
    w.line("Col  int");
    w.dedent();
    w.line("}");
    w.blank();
    w.line(&format!("func (e {}LexError) Error() string {{", name));
    w.indent();
    w.line("return fmt.Sprintf(\"%s at line %d col %d\", e.Msg, e.Line, e.Col)");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("type {}ParseError struct {{", name));
    w.indent();
    w.line("Msg  string");
    w.line("Line int");
    w.line("Col  int");
    w.dedent();
    w.line("}");
    w.blank();
    w.line(&format!("func (e {}ParseError) Error() string {{", name));
    w.indent();
    w.line("return fmt.Sprintf(\"%s at line %d col %d\", e.Msg, e.Line, e.Col)");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("func charInRanges(c rune) bool {");
    w.indent();
    w.line("// Implement based on grammar charset ranges");
    w.line("return false");
    w.dedent();
    w.line("}");
    w.blank();
}
