use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{camel_case, collect_tokens, escape_string, pascal_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct JavaGenerator;

impl CodeGenerator for JavaGenerator {
    fn lang_name(&self) -> &str { "Java" }
    fn file_extension(&self) -> &str { ".java" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("    ");
        let name = &pg.grammar.name;
        let tokens = collect_tokens(pg);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();

        w.line(&format!("import java.util.*;"));
        w.blank();

        w.line(&format!("public class {}Parser {{", name));
        w.indent();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_class(&mut w, name);
        gen_lexer_inner(&mut w, name, pg);
        gen_node_class(&mut w, name, pg);
        gen_parser_inner(&mut w, name, pg);

        w.blank();
        w.line(&format!("public static void main(String[] args) {{"));
        w.indent();
        w.line(&format!("String input = \"1 + 2 * 3\";"));
        w.line(&format!("{}Lexer lexer = new {}Lexer(input);", name, name));
        w.line(&format!("List<{}Token> tokens = lexer.tokenize();", name));
        w.line(&format!("{}Parser parser = new {}Parser(tokens);", name, name));
        w.line(&format!("{}Node tree = parser.parse();", name));
        w.line(&format!("System.out.println(tree);"));
        w.dedent();
        w.line("}");

        w.dedent();
        w.line("}");
        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("public enum {}TokenKind {{", name));
    w.indent();
    for (i, tok) in tokens.iter().enumerate() {
        if i < tokens.len() - 1 {
            w.line(&format!("{},", tok));
        } else {
            w.line(&format!("{}", tok));
        }
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{},", implicit));
        }
    }
    w.line("EOF");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_token_class(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("public static class {}Token {{", name));
    w.indent();
    w.line(&format!("public final {}TokenKind kind;", name));
    w.line("public final String text;");
    w.line("public final int line;");
    w.line("public final int col;");
    w.blank();
    w.line(&format!("public {}Token({}TokenKind kind, String text, int line, int col) {{", name, name));
    w.indent();
    w.line("this.kind = kind;");
    w.line("this.text = text;");
    w.line("this.line = line;");
    w.line("this.col = col;");
    w.dedent();
    w.line("}");
    w.blank();
    w.line("@Override");
    w.line("public String toString() {");
    w.indent();
    w.line("return String.format(\"%s('%s') at %d:%d\", kind, text, line, col);");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer_inner(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("public static class {}Lexer {{", name));
    w.indent();
    w.line("private final String input;");
    w.line("private int pos;");
    w.line("private int line;");
    w.line("private int col;");
    w.blank();

    w.line(&format!("public {}Lexer(String input) {{", name));
    w.indent();
    w.line("this.input = input;");
    w.line("this.pos = 0;");
    w.line("this.line = 1;");
    w.line("this.col = 1;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("public List<{}Token> tokenize() {{", name));
    w.indent();
    w.line(&format!("List<{}Token> tokens = new ArrayList<>();", name));
    w.line("while (pos < input.length()) {");
    w.indent();
    w.line("char c = input.charAt(pos);");
    w.line("if (Character.isWhitespace(c)) { advance(); continue; }");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let method = format!("tryMatch{}", pascal_case(&rule.name));
        w.line(&format!("{}Token {} = {}();", name, camel_case(&rule.name), method));
        w.line(&format!("if ({}) {{", camel_case(&rule.name)));
        w.indent();
        if rule.is_skip() {
            w.line("continue;");
        } else {
            w.line(&format!("tokens.add({}); continue;", camel_case(&rule.name)));
        }
        w.dedent();
        w.line("}");
    }

    for implicit in &pg.implicit_tokens {
        let method = format!("tryMatch{}", implicit);
        w.line(&format!("{}Token {} = {}();", name, camel_case(implicit), method));
        w.line(&format!("if ({}) {{", camel_case(implicit)));
        w.indent();
        w.line(&format!("tokens.add({}); continue;", camel_case(implicit)));
        w.dedent();
        w.line("}");
    }

    w.line(&format!("throw new RuntimeException(String.format(\"Unexpected character '%%c' at line %%d col %%d\", c, line, col));"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokens.add(new {}Token({}TokenKind.EOF, \"\", line, col));", name, name));
    w.line("return tokens;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("private void advance() {");
    w.indent();
    w.line("if (pos < input.length()) {");
    w.indent();
    w.line("if (input.charAt(pos) == '\\n') { line++; col = 1; }");
    w.line("else { col++; }");
    w.line("pos++;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("private char peek(int offset) {");
    w.indent();
    w.line("int p = pos + offset;");
    w.line("return p < input.length() ? input.charAt(p) : '\\0';");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let method = format!("tryMatch{}", pascal_case(&rule.name));
    w.line(&format!("private {}Token {}() {{", name, method));
    w.indent();
    w.line("int savedPos = pos;");
    w.line("int savedLine = line;");
    w.line("int savedCol = col;");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("String target = \"{}\";", escaped));
                w.line("for (int i = 0; i < target.length(); i++) {");
                w.indent();
                w.line("if (peek(i) != target.charAt(i)) { pos = savedPos; return null; }");
                w.dedent();
                w.line("}");
                w.line("String text = input.substring(savedPos, savedPos + target.length());");
                w.line("for (int i = 0; i < target.length(); i++) { advance(); }");
            }
            ElementKind::CharSet(_cs) => {
                w.line("int start = pos;");
                w.line("while (pos < input.length() && charInRange(input.charAt(pos))) { advance(); }");
                w.line("if (pos == start) { return null; }");
                w.line("String text = input.substring(start, pos);");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("int start = pos;");
                                w.line("while (pos < input.length() && charInRange(input.charAt(pos))) { advance(); }");
                                w.line("if (pos == start) { return null; }");
                                w.line("String text = input.substring(start, pos);");
                            }
                            _ => {
                                w.line("String text = input.substring(savedPos, pos);");
                            }
                        }
                    }
                }
            }
            _ => {
                w.line("String text = input.substring(savedPos, pos);");
            }
        }
    } else {
        w.line("String text = input.substring(savedPos, pos);");
    }

    w.blank();
    if rule.is_skip() {
        w.line("return null; // skip");
    } else {
        w.line(&format!("return new {}Token({}TokenKind.{}, text, savedLine, savedCol);", name, name, rule.name));
    }
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let method = format!("tryMatch{}", token_name);
    let lit = token_name_to_literal_java(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("private {}Token {}() {{", name, method));
    w.indent();
    w.line("int savedPos = pos;");
    w.line("int savedLine = line;");
    w.line("int savedCol = col;");
    w.line(&format!("String target = \"{}\";", escaped));
    w.line("for (int i = 0; i < target.length(); i++) {");
    w.indent();
    w.line("if (peek(i) != target.charAt(i)) { pos = savedPos; return null; }");
    w.dedent();
    w.line("}");
    w.line("String text = input.substring(savedPos, savedPos + target.length());");
    w.line("for (int i = 0; i < target.length(); i++) { advance(); }");
    w.line(&format!("return new {}Token({}TokenKind.{}, text, savedLine, savedCol);", name, name, token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal_java(name: &str) -> String {
    let mut result = String::new();
    for c in name.chars() {
        if c.is_ascii_uppercase() {
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

fn gen_node_class(w: &mut super::CodeWriter, name: &str, _pg: &ProcessedGrammar) {
    w.line(&format!("public static class {}Node {{", name));
    w.indent();
    w.line("public final String kind;");
    w.line(&format!("public final List<{}Node> children = new ArrayList<>();", name));
    w.line("public String text;");
    w.line(&format!("public {}TokenKind tokenKind;", name));
    w.blank();

    w.line(&format!("public {}Node(String kind) {{", name));
    w.indent();
    w.line("this.kind = kind;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("public void addChild({}Node child) {{", name));
    w.indent();
    w.line("children.add(child);");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("@Override");
    w.line("public String toString() {");
    w.indent();
    w.line(&format!("return toString(0);"));
    w.dedent();
    w.line("}");
    w.blank();

    w.line("public String toString(int indent) {");
    w.indent();
    w.line("StringBuilder sb = new StringBuilder();");
    w.line("sb.append(\" \".repeat(indent)).append(kind);");
    w.line("if (text != null) sb.append(\": '\").append(text).append(\"'\");");
    w.line("sb.append('\\n');");
    w.line(&format!("for ({}Node child : children) sb.append(child.toString(indent + 2));", name));
    w.line("return sb.toString();");
    w.dedent();
    w.line("}");

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser_inner(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("private final List<{}Token> tokens;", name));
    w.line("private int pos;");
    w.blank();

    w.line(&format!("public {}Parser(List<{}Token> tokens) {{", name, name));
    w.indent();
    w.line("this.tokens = tokens;");
    w.line("this.pos = 0;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("public {}Node parse() {{", name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return parse{}();", pascal_case(&first.name)));
    } else {
        w.line("throw new RuntimeException(\"No parser rules defined\");");
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private {}Token current() {{", name));
    w.indent();
    w.line("return pos < tokens.size() ? tokens.get(pos) : tokens.get(tokens.size() - 1);");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private {}Token matchToken({}TokenKind kind) {{", name, name));
    w.indent();
    w.line("if (current().kind == kind) { return tokens.get(pos++); }");
    w.line("return null;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private {}Token expect({}TokenKind kind) {{", name, name));
    w.indent();
    w.line(&format!("{}Token tok = matchToken(kind);", name));
    w.line("if (tok != null) return tok;");
    w.line(&format!("{}Token cur = current();", name));
    w.line("throw new RuntimeException(String.format(\"Unexpected token %%s ('%%s') at %%d:%%d\", cur.kind, cur.text, cur.line, cur.col));");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let method = format!("parse{}", pascal_case(&rule.name));
    w.line(&format!("private {}Node {}() {{", name, method));
    w.indent();
    w.line(&format!("{}Node node = new {}Node(\"{}\");", name, name, rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node;");
    } else {
        w.line(&format!("switch (current().kind) {{", ));
        w.indent();
        for alt in &rule.alternatives {
            let first_elem = alt.elements.first();
            let match_arm = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("case {}:", tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("case {}:", tok_name)
                    }
                    _ => "default:".to_string(),
                }
            } else {
                "default:".to_string()
            };
            w.line(&match_arm);
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node;");
            w.dedent();
        }
        w.line("default:");
        w.indent();
        w.line(&format!("throw new RuntimeException(\"Unexpected token: \" + current().kind);"));
        w.dedent();
        w.dedent();
        w.line("}");
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("{{ {}Token t = expect({}TokenKind.{}); {}Node n = new {}Node(\"Token\"); n.text = t.text; n.tokenKind = t.kind; node.addChild(n); }}", name, name, tok, name, name));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("{{ {}Token t = expect({}TokenKind.{}); {}Node n = new {}Node(\"Token\"); n.text = t.text; n.tokenKind = t.kind; node.addChild(n); }}", name, name, tok_name, name, name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("node.addChild(parse{}());", pascal_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("int saved = pos;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (Exception e) { pos = saved; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("while (true) {");
                w.indent();
                w.line("int saved = pos;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (Exception e) { pos = saved; break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("while (true) {");
                w.indent();
                w.line("int saved = pos;");
                w.line("try {");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("} catch (Exception e) { pos = saved; break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}
