use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{collect_tokens, escape_string, snake_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct PythonGenerator;

impl CodeGenerator for PythonGenerator {
    fn lang_name(&self) -> &str { "Python" }
    fn file_extension(&self) -> &str { ".py" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("    ");
        let name = &pg.grammar.name;
        let tokens = collect_tokens(pg);

        w.line("\"\"\"Generated by pargen - do not edit manually\"\"\"");
        w.line("from __future__ import annotations");
        w.line("from dataclasses import dataclass, field");
        w.line("from enum import Enum, auto");
        w.line("from typing import List, Optional");
        w.blank();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_class(&mut w, name);
        gen_lexer_class(&mut w, name, pg);
        gen_node_class(&mut w, name, pg);
        gen_parser_class(&mut w, name, pg);

        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("class {}TokenKind(Enum):", name));
    w.indent();
    w.line("Eof = auto()");
    for tok in tokens {
        w.line(&format!("{} = auto()", tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{} = auto()", implicit));
        }
    }
    w.dedent();
    w.blank();
}

fn gen_token_class(w: &mut super::CodeWriter, name: &str) {
    w.line("@dataclass");
    w.line(&format!("class {}Token:", name));
    w.indent();
    w.line(&format!("kind: {}TokenKind", name));
    w.line("text: str = \"\"");
    w.line("line: int = 0");
    w.line("col: int = 0");
    w.dedent();
    w.blank();
}

fn gen_lexer_class(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("class {}Lexer:", name));
    w.indent();

    w.line("def __init__(self, input: str):");
    w.indent();
    w.line("self.input = input");
    w.line("self.pos = 0");
    w.line("self.line = 1");
    w.line("self.col = 1");
    w.dedent();
    w.blank();

    w.line(&format!("def tokenize(self) -> List[{}Token]:", name));
    w.indent();
    w.line(&format!("tokens: List[{}Token] = []", name));
    w.line("while self.pos < len(self.input):");
    w.indent();
    w.line("c = self.input[self.pos]");
    w.line("if c in ' \\t\\n\\r':");
    w.indent();
    w.line("self._advance()");
    w.line("continue");
    w.dedent();

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let fn_name = format!("_try_match_{}", snake_case(&rule.name));
        w.line(&format!("tok = self.{}()", fn_name));
        w.line("if tok is not None:");
        w.indent();
        if rule.is_skip() {
            w.line("continue");
        } else {
            w.line("tokens.append(tok)");
            w.line("continue");
        }
        w.dedent();
    }

    for implicit in &pg.implicit_tokens {
        let fn_name = format!("_try_match_{}", snake_case(implicit));
        w.line(&format!("tok = self.{}()", fn_name));
        w.line("if tok is not None:");
        w.indent();
        w.line("tokens.append(tok)");
        w.line("continue");
        w.dedent();
    }

    w.line(&format!("raise ValueError(f'Unexpected character {{self.input[self.pos]!r}} at line {{self.line}} col {{self.col}}')"));
    w.dedent();
    w.blank();

    w.line(&format!("tokens.append({}Token(kind={}TokenKind.Eof, line=self.line, col=self.col))", name, name));
    w.line("return tokens");
    w.dedent();
    w.blank();

    w.line("def _advance(self) -> None:");
    w.indent();
    w.line("if self.pos < len(self.input):");
    w.indent();
    w.line("if self.input[self.pos] == '\\n':");
    w.indent();
    w.line("self.line += 1");
    w.line("self.col = 1");
    w.dedent();
    w.line("else:");
    w.indent();
    w.line("self.col += 1");
    w.dedent();
    w.line("self.pos += 1");
    w.dedent();
    w.dedent();
    w.blank();

    w.line("def _peek(self, offset: int = 0) -> str | None:");
    w.indent();
    w.line("pos = self.pos + offset");
    w.line("if pos < len(self.input): return self.input[pos]");
    w.line("return None");
    w.dedent();
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }

    w.dedent();
    w.blank();
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("_try_match_{}", snake_case(&rule.name));
    w.line(&format!("def {}(self) -> Optional[{}Token]:", fn_name, name));
    w.indent();
    w.line("saved_pos = self.pos");
    w.line("saved_line = self.line");
    w.line("saved_col = self.col");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("target = \"{}\"", escaped));
                w.line("for i, c in enumerate(target):");
                w.indent();
                w.line("if self._peek(i) != c:");
                w.indent();
                w.line("self.pos = saved_pos");
                w.line("return None");
                w.dedent();
                w.dedent();
                w.line("text = self.input[saved_pos:saved_pos + len(target)]");
                w.line("for _ in target: self._advance()");
            }
            ElementKind::CharSet(_cs) => {
                w.line("start = self.pos");
                w.line("while self.pos < len(self.input) and self._char_in_range(self.input[self.pos]):");
                w.indent();
                w.line("self._advance()");
                w.dedent();
                w.line("if self.pos == start:");
                w.indent();
                w.line("return None");
                w.dedent();
                w.line("text = self.input[start:self.pos]");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("start = self.pos");
                                w.line("while self.pos < len(self.input) and self._char_in_range(self.input[self.pos]):");
                                w.indent();
                                w.line("self._advance()");
                                w.dedent();
                                w.line("if self.pos == start: return None");
                                w.line("text = self.input[start:self.pos]");
                            }
                            _ => {
                                w.line("text = ''");
                            }
                        }
                    }
                }
            }
            _ => {
                w.line("text = self.input[saved_pos:self.pos]");
            }
        }
    } else {
        w.line("text = self.input[saved_pos:self.pos]");
    }

    w.blank();
    if rule.is_skip() {
        w.line("return None  # skip");
    } else {
        w.line(&format!("return {}Token(kind={}TokenKind.{}, text=text, line=saved_line, col=saved_col)", name, name, rule.name));
    }
    w.dedent();
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let fn_name = format!("_try_match_{}", snake_case(token_name));
    let lit = token_name_to_literal_py(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("def {}(self) -> Optional[{}Token]:", fn_name, name));
    w.indent();
    w.line("saved_pos = self.pos");
    w.line("saved_line = self.line");
    w.line("saved_col = self.col");
    w.line(&format!("target = \"{}\"", escaped));
    w.line("for i, c in enumerate(target):");
    w.indent();
    w.line("if self._peek(i) != c:");
    w.indent();
    w.line("self.pos = saved_pos");
    w.line("return None");
    w.dedent();
    w.dedent();
    w.line("text = self.input[saved_pos:saved_pos + len(target)]");
    w.line("for _ in target: self._advance()");
    w.line(&format!("return {}Token(kind={}TokenKind.{}, text=text, line=saved_line, col=saved_col)", name, name, token_name));
    w.dedent();
    w.blank();
}

fn token_name_to_literal_py(name: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = name.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if i > 0 && chars[i].is_ascii_uppercase() {
            result.push(chars[i].to_ascii_lowercase());
        } else {
            result.push(chars[i].to_ascii_lowercase());
        }
        i += 1;
    }
    result
}

fn gen_node_class(w: &mut super::CodeWriter, name: &str, _pg: &ProcessedGrammar) {
    w.line("@dataclass");
    w.line(&format!("class {}Node:", name));
    w.indent();
    w.line("kind: str = \"\"");
    w.line(&format!("children: List[{}Node] = field(default_factory=list)", name));
    w.line("text: Optional[str] = None");
    w.line(&format!("token_kind: Optional[{}TokenKind] = None", name));
    w.dedent();
    w.blank();
}

fn gen_parser_class(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("class {}Parser:", name));
    w.indent();

    w.line(&format!("def __init__(self, tokens: List[{}Token]):", name));
    w.indent();
    w.line("self.tokens = tokens");
    w.line("self.pos = 0");
    w.dedent();
    w.blank();

    w.line(&format!("def parse(self) -> {}Node:", name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return self._parse_{}()", snake_case(&first.name)));
    } else {
        w.line("raise ValueError('No parser rules defined')");
    }
    w.dedent();
    w.blank();

    w.line(&format!("def _current(self) -> {}Token:", name));
    w.indent();
    w.line("if self.pos < len(self.tokens): return self.tokens[self.pos]");
    w.line("return self.tokens[-1]");
    w.dedent();
    w.blank();

    w.line(&format!("def _match(self, kind: {}TokenKind) -> Optional[{}Token]:", name, name));
    w.indent();
    w.line("if self._current().kind == kind:");
    w.indent();
    w.line("tok = self.tokens[self.pos]");
    w.line("self.pos += 1");
    w.line("return tok");
    w.dedent();
    w.line("return None");
    w.dedent();
    w.blank();

    w.line(&format!("def _expect(self, kind: {}TokenKind) -> {}Token:", name, name));
    w.indent();
    w.line("tok = self._match(kind)");
    w.line("if tok is not None: return tok");
    w.line("cur = self._current()");
    w.line(&format!("raise ValueError(f'Unexpected token {{cur.kind}} (\"{{cur.text}}\") at line {{cur.line}} col {{cur.col}}')"));
    w.dedent();
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }

    w.dedent();
    w.blank();
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("_parse_{}", snake_case(&rule.name));
    w.line(&format!("def {}(self) -> {}Node:", fn_name, name));
    w.indent();
    w.line(&format!("node = {}Node(kind=\"{}\")", name, rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node");
    } else {
        w.line("cur = self._current()");
        w.line("if False: pass");
        for alt in &rule.alternatives {
            let first_elem = alt.elements.first();
            let condition = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => {
                        format!("elif cur.kind == {}TokenKind.{}:", name, tok)
                    }
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("elif cur.kind == {}TokenKind.{}:", name, tok_name)
                    }
                    _ => "else:".to_string(),
                }
            } else {
                "else:".to_string()
            };
            w.line(&condition);
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node");
            w.dedent();
        }
        w.line("else:");
        w.indent();
        w.line(&format!("raise ValueError(f'Unexpected token {{cur.kind}} at line {{cur.line}}')"));
        w.dedent();
    }

    w.dedent();
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("tok = self._expect({}TokenKind.{})", name, tok));
                w.line(&format!("node.children.append({}Node(kind='Token', text=tok.text, token_kind=tok.kind))", name));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("tok = self._expect({}TokenKind.{})", name, tok_name));
                w.line(&format!("node.children.append({}Node(kind='Token', text=tok.text, token_kind=tok.kind))", name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("node.children.append(self._parse_{}())", snake_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("saved = self.pos");
                w.line("try:");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("except ValueError:");
                w.indent();
                w.line("self.pos = saved");
                w.dedent();
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("while True:");
                w.indent();
                w.line("saved = self.pos");
                w.line("try:");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("except ValueError:");
                w.indent();
                w.line("self.pos = saved");
                w.line("break");
                w.dedent();
                w.dedent();
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("while True:");
                w.indent();
                w.line("saved = self.pos");
                w.line("try:");
                w.indent();
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.dedent();
                w.line("except ValueError:");
                w.indent();
                w.line("self.pos = saved");
                w.line("break");
                w.dedent();
                w.dedent();
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}
