use crate::analysis::ProcessedGrammar;
use crate::codegen::{collect_tokens, escape_string, snake_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct RustGenerator;

impl CodeGenerator for RustGenerator {
    fn lang_name(&self) -> &str { "Rust" }
    fn file_extension(&self) -> &str { ".rs" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("    ");
        let name = &pg.grammar.name;
        let tokens = collect_tokens(pg);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();
        w.line("#![allow(dead_code, unused_variables, unused_mut)]");
        w.blank();
        w.line("use std::fmt;");
        w.blank();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_struct(&mut w, name);
        gen_lexer(&mut w, name, pg);
        gen_cst_node(&mut w, name, pg);
        gen_parser(&mut w, name, pg);
        gen_error(&mut w, name);

        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
    w.line(&format!("pub enum {}TokenKind {{", name));
    w.indent();
    for tok in tokens {
        if *tok == pg.grammar.rules.iter().find(|r| r.is_lexer_rule()).map(|r| r.name.clone()).unwrap_or_default() {
        }
        w.line(&format!("{},", tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{},", implicit));
        }
    }
    w.line("Eof,");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl fmt::Display for {}TokenKind {{", name));
    w.indent();
    w.line("fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {");
    w.indent();
    w.line("match self {");
    w.indent();
    for tok in tokens {
        w.line(&format!("{name}TokenKind::{tok} => write!(f, \"{tok}\"),"));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{name}TokenKind::{implicit} => write!(f, \"{implicit}\"),"));
        }
    }
    w.line(&format!("{name}TokenKind::Eof => write!(f, \"EOF\"),"));
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_token_struct(w: &mut super::CodeWriter, name: &str) {
    w.line("#[derive(Debug, Clone)]");
    w.line(&format!("pub struct {}Token {{", name));
    w.indent();
    w.line(&format!("pub kind: {}TokenKind,", name));
    w.line("pub text: String,");
    w.line("pub line: usize,");
    w.line("pub col: usize,");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("pub struct {}Lexer {{", name));
    w.indent();
    w.line("input: Vec<char>,");
    w.line("pos: usize,");
    w.line("line: usize,");
    w.line("col: usize,");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl {}Lexer {{", name));
    w.indent();
    w.line("pub fn new(input: &str) -> Self {");
    w.indent();
    w.line("Self { input: input.chars().collect(), pos: 0, line: 1, col: 1 }");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("pub fn tokenize(&mut self) -> Result<Vec<{}Token>, {}LexError> {{", name, name));
    w.indent();
    w.line("let mut tokens = Vec::new();");
    w.line("while self.pos < self.input.len() {");
    w.indent();
    w.line("let c = self.input[self.pos];");
    w.line("if c.is_whitespace() {");
    w.indent();
    w.line("self.advance();");
    w.line("continue;");
    w.dedent();
    w.line("}");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let fn_name = format!("try_match_{}", snake_case(&rule.name));
        w.line(&format!("if let Some(token) = self.{}() {{", fn_name));
        w.indent();
        w.line("tokens.push(token);");
        w.line("continue;");
        w.dedent();
        w.line("}");
    }

    for implicit in &pg.implicit_tokens {
        let fn_name = format!("try_match_{}", snake_case(implicit));
        w.line(&format!("if let Some(token) = self.{}() {{", fn_name));
        w.indent();
        w.line("tokens.push(token);");
        w.line("continue;");
        w.dedent();
        w.line("}");
    }

    w.line(&format!("return Err({}LexError::UnexpectedChar(c, self.line, self.col));", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokens.push({}Token {{ kind: {}TokenKind::Eof, text: String::new(), line: self.line, col: self.col }});", name, name));
    w.line("Ok(tokens)");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("fn advance(&mut self) {");
    w.indent();
    w.line("if self.pos < self.input.len() {");
    w.indent();
    w.line("if self.input[self.pos] == '\\n' { self.line += 1; self.col = 1; }");
    w.line("else { self.col += 1; }");
    w.line("self.pos += 1;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("fn peek(&self) -> Option<char> {");
    w.indent();
    w.line("self.input.get(self.pos).copied()");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("fn peek_at(&self, offset: usize) -> Option<char> {");
    w.indent();
    w.line("self.input.get(self.pos + offset).copied()");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("fn make_token(&self, kind: {}TokenKind, text: String, start_line: usize, start_col: usize) -> {}Token {{", name, name));
    w.indent();
    w.line(&format!("{name}Token {{ kind, text, line: start_line, col: start_col }}"));
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule, pg);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_token_match_fn(w, name, implicit);
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule, _pg: &ProcessedGrammar) {
    let fn_name = format!("try_match_{}", snake_case(&rule.name));
    w.line(&format!("fn {}(&mut self) -> Option<{}Token> {{", fn_name, name));
    w.indent();

    let is_skip = rule.is_skip();
    let saved_pos_stmt = "let saved_pos = self.pos;\n        let saved_line = self.line;\n        let saved_col = self.col;";
    w.line(saved_pos_stmt);
    w.blank();

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("let target = \"{}\";", escaped));
                w.line("for (i, c) in target.chars().enumerate() {");
                w.indent();
                w.line("if self.peek_at(i) != Some(c) { return None; }");
                w.dedent();
                w.line("}");
                w.line("for _ in target.chars() { self.advance(); }");
                w.line(&format!("let text = self.input[saved_pos..self.pos].iter().collect::<String>();"));
            }
            ElementKind::CharSet(cs) => {
                let class = cs.to_regex_class();
                w.line(&format!("// charset: {}", class));
                w.line("let mut len = 0;");
                w.line("while let Some(c) = self.peek_at(len) {");
                w.indent();
                w.line("if Self::char_in_ranges(c, &RANGES) { len += 1; } else { break; }");
                w.dedent();
                w.line("}");
                w.line("if len == 0 { return None; }");
                w.line("for _ in 0..len { self.advance(); }");
                w.line("let text = self.input[saved_pos..self.pos].iter().collect::<String>();");
            }
            ElementKind::OneOrMore(block) => {
                gen_lexer_element_match(w, &block.alternatives[0].elements[0].kind);
                w.line("let text = self.input[saved_pos..self.pos].iter().collect::<String>();");
            }
            _ => {
                w.line("let mut len = 0;");
                w.line("while self.pos + len < self.input.len() {");
                w.indent();
                w.line("len += 1;");
                w.dedent();
                w.line("}");
                w.line("if len == 0 { return None; }");
                w.line("for _ in 0..len { self.advance(); }");
                w.line("let text = self.input[saved_pos..self.pos].iter().collect::<String>();");
            }
        }
    } else {
        w.line("let mut len = 0;");
        w.line("while self.pos + len < self.input.len() {");
        w.indent();
        w.line("len += 1;");
        w.dedent();
        w.line("}");
        w.line("if len == 0 { return None; }");
        w.line("for _ in 0..len { self.advance(); }");
        w.line("let text = self.input[saved_pos..self.pos].iter().collect::<String>();");
    }

    w.blank();
    if is_skip {
        w.line("None");
    } else {
        w.line(&format!("Some(self.make_token({}TokenKind::{}, text, saved_line, saved_col))", name, rule.name));
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer_element_match(w: &mut super::CodeWriter, kind: &ElementKind) {
    match kind {
        ElementKind::CharSet(cs) => {
            let class = cs.to_regex_class();
            w.line(&format!("// match one or more of charset: {}", class));
            w.line("let mut len = 0;");
            w.line("while let Some(c) = self.peek_at(len) {");
            w.indent();
            w.line("if Self::char_in_ranges(c, &RANGES) { len += 1; } else { break; }");
            w.dedent();
            w.line("}");
            w.line("if len == 0 { self.pos = saved_pos; return None; }");
            w.line("for _ in 0..len { self.advance(); }");
        }
        ElementKind::StringLiteral(lit) => {
            let escaped = escape_string(lit);
            w.line(&format!("let target = \"{}\";", escaped));
            w.line("for (i, c) in target.chars().enumerate() {");
            w.indent();
            w.line("if self.peek_at(i) != Some(c) { self.pos = saved_pos; return None; }");
            w.dedent();
            w.line("}");
            w.line("for _ in target.chars() { self.advance(); }");
        }
        _ => {}
    }
}

fn gen_implicit_token_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let fn_name = format!("try_match_{}", snake_case(token_name));

    let lit = token_name_to_literal(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("fn {}(&mut self) -> Option<{}Token> {{", fn_name, name));
    w.indent();
    w.line("let saved_pos = self.pos;");
    w.line("let saved_line = self.line;");
    w.line("let saved_col = self.col;");
    w.line(&format!("let target = \"{}\";", escaped));
    w.line("for (i, c) in target.chars().enumerate() {");
    w.indent();
    w.line("if self.peek_at(i) != Some(c) { return None; }");
    w.dedent();
    w.line("}");
    w.line("for _ in target.chars() { self.advance(); }");
    w.line("let text = self.input[saved_pos..self.pos].iter().collect::<String>();");
    w.line(&format!("Some(self.make_token({}TokenKind::{}, text, saved_line, saved_col))", name, token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal(name: &str) -> String {
    let mut result = String::new();
    let mut i = 0;
    let chars: Vec<char> = name.chars().collect();
    while i < chars.len() {
        if i + 1 < chars.len() && chars[i].is_ascii_uppercase() && chars[i + 1].is_ascii_lowercase() {
            result.push(chars[i].to_ascii_lowercase());
            i += 1;
        } else if i > 0 && chars[i].is_ascii_uppercase() && (i + 1 >= chars.len() || chars[i + 1].is_ascii_uppercase()) {
            result.push(chars[i].to_ascii_lowercase());
            i += 1;
        } else if chars[i].is_ascii_uppercase() {
            result.push(chars[i].to_ascii_lowercase());
            i += 1;
        } else {
            result.push(chars[i]);
            i += 1;
        }
    }
    result
}

fn gen_cst_node(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line("#[derive(Debug, Clone)]");
    w.line(&format!("pub enum {}Node {{", name));
    w.indent();

    for rule in &pg.transformed_rules {
        w.line(&format!("{} {{ children: Vec<{}Node> }},", rule.name, name));
    }
    for rule in pg.grammar.parser_rules() {
        if !pg.transformed_rules.iter().any(|r| r.name == rule.name) {
            w.line(&format!("{} {{ children: Vec<{}Node> }},", rule.name, name));
        }
    }
    w.line(&format!("Token {{ kind: {}TokenKind, text: String }},", name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("pub struct {}Parser {{", name));
    w.indent();
    w.line(&format!("tokens: Vec<{}Token>,", name));
    w.line("pos: usize,");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl {}Parser {{", name));
    w.indent();

    w.line(&format!("pub fn new(tokens: Vec<{}Token>) -> Self {{", name));
    w.indent();
    w.line("Self { tokens, pos: 0 }");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("pub fn parse(&mut self) -> Result<{}Node, {}ParseError> {{", name, name));
    w.indent();

    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();

    if let Some(first_rule) = all_parser_rules.first() {
        w.line(&format!("self.parse_{}()", snake_case(&first_rule.name)));
    } else {
        w.line(&format!("Err({}ParseError::NoRules)", name));
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("fn current(&self) -> &{}Token {{", name));
    w.indent();
    w.line("self.tokens.get(self.pos).unwrap_or_else(|| self.tokens.last().unwrap())");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("fn match_token(&mut self, kind: {}TokenKind) -> Option<&{}Token> {{", name, name));
    w.indent();
    w.line("if self.current().kind == kind {");
    w.indent();
    w.line("let tok = &self.tokens[self.pos];");
    w.line("self.pos += 1;");
    w.line("Some(tok)");
    w.dedent();
    w.line("} else {");
    w.indent();
    w.line("None");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("fn expect(&mut self, kind: {}TokenKind) -> Result<&{}Token, {}ParseError> {{", name, name, name));
    w.indent();
    w.line("if let Some(_tok) = self.match_token(kind) {");
    w.indent();
    w.line("Ok(&self.tokens[self.pos - 1])");
    w.dedent();
    w.line("} else {");
    w.indent();
    w.line("let cur = self.current();");
    w.line(&format!("Err({}ParseError::UnexpectedToken(cur.kind, cur.text.clone(), cur.line, cur.col))", name));
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule, pg);
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule, _pg: &ProcessedGrammar) {
    let fn_name = format!("parse_{}", snake_case(&rule.name));
    w.line(&format!("fn {}(&mut self) -> Result<{}Node, {}ParseError> {{", fn_name, name, name));
    w.indent();
    w.line(&format!("let mut children: Vec<{}Node> = Vec::new();", name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line(&format!("Ok({}Node::{} {{ children }})", name, rule.name));
    } else {
        w.line("match self.current().kind {");
        w.indent();
        for (i, alt) in rule.alternatives.iter().enumerate() {
            let first_elem = alt.elements.first();
            let match_kind = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("{}TokenKind::{}", name, tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = crate::analysis::first_follow::string_literal_to_token_name(lit);
                        format!("{}TokenKind::{}", name, tok_name)
                    }
                    ElementKind::RuleRef(r) => {
                        format!("_ if self.is_{}_first() =>", snake_case(r))
                    }
                    _ => "_".to_string(),
                }
            } else {
                "_".to_string()
            };

            if match_kind.starts_with("_ if") {
                w.line(&format!("{} {{", match_kind));
            } else if i == rule.alternatives.len() - 1 {
                w.line("_ => {");
            } else {
                w.line(&format!("{} => {{", match_kind));
            }
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line(&format!("return Ok({}Node::{} {{ children }});", name, rule.name));
            w.dedent();
            w.line("}");
        }
        w.dedent();
        w.line("}");
        let cur = "self.current()";
        w.line(&format!("Err({}ParseError::UnexpectedToken({}.kind, {}.text.clone(), {}.line, {}.col))", name, cur, cur, cur, cur));
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("children.push({}Node::Token {{ kind: {}TokenKind::{}, text: self.expect({}TokenKind::{})?.text.clone() }});", name, name, tok, name, tok));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = crate::analysis::first_follow::string_literal_to_token_name(lit);
                w.line(&format!("children.push({}Node::Token {{ kind: {}TokenKind::{}, text: self.expect({}TokenKind::{})?.text.clone() }});", name, name, tok_name, name, tok_name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("children.push(self.parse_{}()?);", snake_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("let saved = self.pos;");
                let mut matched = false;
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                    matched = true;
                }
                if !matched {
                    w.line("// empty optional");
                }
                w.dedent();
                w.line("}");
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("loop {");
                w.indent();
                w.line("let saved = self.pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if self.pos == saved { break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("loop {");
                w.indent();
                w.line("let saved = self.pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if self.pos == saved { break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            ElementKind::Dot => {
                w.line("// wildcard - match any token");
                w.line(&format!("if self.current().kind != {}TokenKind::Eof {{", name));
                w.indent();
                w.line("let tok = self.current().clone();");
                w.line(&format!("children.push({}Node::Token {{ kind: tok.kind, text: tok.text.clone() }});", name));
                w.line("self.pos += 1;");
                w.dedent();
                w.line("}");
            }
            ElementKind::Action(_) | ElementKind::Predicate(_) => {}
            ElementKind::Range(_, _) | ElementKind::CharSet(_) | ElementKind::Not(_) => {}
        }
    }
}

fn gen_error(w: &mut super::CodeWriter, name: &str) {
    w.line("#[derive(Debug)]");
    w.line(&format!("pub enum {}LexError {{", name));
    w.indent();
    w.line("UnexpectedChar(char, usize, usize),");
    w.line("UnterminatedString(usize),");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl fmt::Display for {}LexError {{", name));
    w.indent();
    w.line("fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {");
    w.indent();
    w.line("match self {");
    w.indent();
    w.line(&format!("{}LexError::UnexpectedChar(c, line, col) => write!(f, \"Unexpected character '{{}}' at line {{}} col {{}}\", c, line, col),", name));
    w.line(&format!("{}LexError::UnterminatedString(line) => write!(f, \"Unterminated string at line {{}}\", line),", name));
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl std::error::Error for {}LexError {{}}", name));
    w.blank();

    w.line("#[derive(Debug)]");
    w.line(&format!("pub enum {}ParseError {{", name));
    w.indent();
    w.line(&format!("UnexpectedToken({}TokenKind, String, usize, usize),", name));
    w.line("NoRules,");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl fmt::Display for {}ParseError {{", name));
    w.indent();
    w.line("fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {");
    w.indent();
    w.line("match self {");
    w.indent();
    w.line(&format!("{}ParseError::UnexpectedToken(kind, text, line, col) => write!(f, \"Unexpected token '{{}}' ('{{}}') at line {{}} col {{}}\", kind, text, line, col),", name));
    w.line(&format!("{}ParseError::NoRules => write!(f, \"No parser rules defined\"),", name));
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("impl std::error::Error for {}ParseError {{}}", name));
    w.blank();
}
