use crate::analysis::ProcessedGrammar;
use crate::codegen::{escape_string, snake_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct TreeSitterGenerator;

impl CodeGenerator for TreeSitterGenerator {
    fn lang_name(&self) -> &str { "Tree-sitter" }
    fn file_extension(&self) -> &str { ".js" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("  ");
        let name = snake_case(&pg.grammar.name);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();
        w.line("module.exports = grammar({");
        w.indent();
        w.line(&format!("name: '{}',", name));
        w.blank();

        // Extras: whitespace and comments (skip tokens)
        gen_extras(&mut w, pg);
        w.blank();

        // Word token (optional, for keyword matching)
        if let Some(word_rule) = find_word_rule(pg) {
            w.line(&format!("word: $ => {},", ts_ref(&word_rule)));
            w.blank();
        }

        w.line("rules: {");
        w.indent();

        let parser_rules: Vec<&Rule> = pg.grammar.rules.iter().filter(|r| r.is_parser_rule()).collect();
        let lexer_rules: Vec<&Rule> = pg.grammar.rules.iter().filter(|r| r.is_lexer_rule()).collect();

        for rule in &parser_rules {
            gen_rule(&mut w, rule);
        }

        for rule in &lexer_rules {
            gen_lexer_rule(&mut w, rule);
        }

        // Implicit tokens from string literals
        for tok in &pg.implicit_tokens {
            gen_implicit_token(&mut w, tok);
        }

        w.dedent();
        w.line("}");

        w.dedent();
        w.line("});");

        w.to_string()
    }
}

fn find_word_rule(pg: &ProcessedGrammar) -> Option<String> {
    pg.grammar.rules.iter()
        .find(|r| r.is_lexer_rule() && r.name.to_lowercase() == "id")
        .map(|r| snake_case(&r.name))
}

fn gen_extras(w: &mut super::CodeWriter, pg: &ProcessedGrammar) {
    let skip_rules: Vec<&Rule> = pg.grammar.rules.iter().filter(|r| r.is_skip()).collect();
    if skip_rules.is_empty() {
        w.line("extras: $ => [/\\s+/],");
        return;
    }

    w.line("extras: $ => [");
    w.indent();
    w.line("/\\s+/,");
    for rule in &skip_rules {
        w.line(&format!("$.{},", snake_case(&rule.name)));
    }
    w.dedent();
    w.line("],");
}

fn gen_rule(w: &mut super::CodeWriter, rule: &Rule) {
    let name = snake_case(&rule.name);
    if rule.alternatives.len() == 1 {
        let body = gen_alternative_body(&rule.alternatives[0]);
        w.line(&format!("{}: $ => {},", name, body));
    } else {
        w.line(&format!("{}: $ => choice(", name));
        w.indent();
        for (i, alt) in rule.alternatives.iter().enumerate() {
            let body = gen_alternative_body(alt);
            if i == rule.alternatives.len() - 1 {
                w.line(&format!("{}", body));
            } else {
                w.line(&format!("{},", body));
            }
        }
        w.dedent();
        w.line("),");
    }
}

fn gen_lexer_rule(w: &mut super::CodeWriter, rule: &Rule) {
    let name = snake_case(&rule.name);
    let body = gen_alternative_body(&rule.alternatives[0]);
    w.line(&format!("{}: $ => token({}),", name, body));
}

fn gen_implicit_token(w: &mut super::CodeWriter, tok: &str) {
    let name = snake_case(tok);
    w.line(&format!("{}: $ => {},", name, ts_string_literal(tok)));
}

fn gen_alternative_body(alt: &Alternative) -> String {
    if alt.elements.is_empty() {
        return "''".to_string();
    }
    if alt.elements.len() == 1 {
        return gen_element(&alt.elements[0]);
    }
    let parts: Vec<String> = alt.elements.iter().map(gen_element).collect();
    format!("seq({})", parts.join(", "))
}

fn gen_element(elem: &Element) -> String {
    match &elem.kind {
        ElementKind::RuleRef(name) => ts_ref(name),
        ElementKind::TokenRef(name) => ts_ref(name),
        ElementKind::StringLiteral(text) => ts_string_literal(text),
        ElementKind::CharSet(cs) => ts_charset(cs),
        ElementKind::Optional(block) => {
            let body = gen_alt_block(block);
            format!("optional({})", body)
        }
        ElementKind::ZeroOrMore(block) => {
            let body = gen_alt_block(block);
            format!("repeat({})", body)
        }
        ElementKind::OneOrMore(block) => {
            let body = gen_alt_block(block);
            format!("repeat1({})", body)
        }
        ElementKind::Group(block) => gen_alt_block(block),
        ElementKind::Dot => "/./".to_string(),
        ElementKind::Range(start, end) => format!("/{}/", escape_regex_range(start, end)),
        ElementKind::Predicate(_) => "''".to_string(), // tree-sitter doesn't support predicates
        ElementKind::Action(_) => "''".to_string(),    // actions not supported
        ElementKind::Not(inner) => {
            let body = match inner.as_ref() {
                ElementKind::StringLiteral(text) => ts_string_literal(text),
                _ => "''".to_string(),
            };
            format!("prec(-1, seq({}, {}))", body, body) // placeholder
        }
    }
}

fn gen_alt_block(block: &AltBlock) -> String {
    if block.alternatives.len() == 1 {
        gen_alternative_body(&block.alternatives[0])
    } else {
        let parts: Vec<String> = block.alternatives.iter().map(gen_alternative_body).collect();
        format!("choice({})", parts.join(", "))
    }
}

fn ts_ref(name: &str) -> String {
    format!("$.{}", snake_case(name))
}

fn ts_string_literal(text: &str) -> String {
    format!("'{}'", escape_string(text))
}

fn ts_charset(cs: &CharSetDef) -> String {
    let inner: String = cs.ranges.iter().map(|r| {
        if r.start == r.end {
            regex_escape_char(r.start)
        } else {
            format!("{}-{}", regex_escape_char(r.start), regex_escape_char(r.end))
        }
    }).collect();

    if cs.negated {
        format!("/[^{}]+/", inner)
    } else {
        format!("/[{}]+/", inner)
    }
}

fn regex_escape_char(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        ']' => "\\]".to_string(),
        '-' => "\\-".to_string(),
        '^' => "\\^".to_string(),
        '/' => "\\/".to_string(),
        _ if c.is_ascii_alphanumeric() => c.to_string(),
        _ => format!("\\u{{{:04X}}}", c as u32),
    }
}

fn escape_regex_range(start: &str, end: &str) -> String {
    format!("{}-{}", regex_escape_str(start), regex_escape_str(end))
}

fn regex_escape_str(s: &str) -> String {
    s.chars().map(regex_escape_char).collect()
}
