use crate::analysis::ProcessedGrammar;
use crate::analysis::first_follow::string_literal_to_token_name;
use crate::codegen::{camel_case, collect_tokens, escape_string, pascal_case, CodeGenerator};
use crate::grammar::ast::*;

pub struct TypeScriptGenerator;

impl CodeGenerator for TypeScriptGenerator {
    fn lang_name(&self) -> &str { "TypeScript" }
    fn file_extension(&self) -> &str { ".ts" }

    fn generate(&self, pg: &ProcessedGrammar) -> String {
        let mut w = super::CodeWriter::new("  ");
        let name = &pg.grammar.name;
        let tokens = collect_tokens(pg);

        w.line("// Generated by pargen - do not edit manually");
        w.blank();

        gen_token_enum(&mut w, name, &tokens, pg);
        gen_token_interface(&mut w, name);
        gen_lexer(&mut w, name, pg);
        gen_node(&mut w, name, pg);
        gen_parser(&mut w, name, pg);

        w.to_string()
    }
}

fn gen_token_enum(w: &mut super::CodeWriter, name: &str, tokens: &[String], pg: &ProcessedGrammar) {
    w.line(&format!("export enum {}TokenKind {{", name));
    w.indent();
    for tok in tokens {
        w.line(&format!("{},", tok));
    }
    for implicit in &pg.implicit_tokens {
        if !tokens.contains(implicit) {
            w.line(&format!("{},", implicit));
        }
    }
    w.line("Eof = 'EOF',");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_token_interface(w: &mut super::CodeWriter, name: &str) {
    w.line(&format!("export interface {}Token {{", name));
    w.indent();
    w.line(&format!("kind: {}TokenKind;", name));
    w.line("text: string;");
    w.line("line: number;");
    w.line("col: number;");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("export class {}Lexer {{", name));
    w.indent();
    w.line("private input: string;");
    w.line("private pos: number;");
    w.line("private line: number;");
    w.line("private col: number;");
    w.blank();

    w.line("constructor(input: string) {");
    w.indent();
    w.line("this.input = input;");
    w.line("this.pos = 0;");
    w.line("this.line = 1;");
    w.line("this.col = 1;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokenize(): {}Token[] {{", name));
    w.indent();
    w.line(&format!("const tokens: {}Token[] = [];", name));
    w.line("while (this.pos < this.input.length) {");
    w.indent();
    w.line("const c = this.input[this.pos];");
    w.line("if (c === ' ' || c === '\\t' || c === '\\n' || c === '\\r') {");
    w.indent();
    w.line("this.advance(); continue;");
    w.dedent();
    w.line("}");

    for rule in pg.lexer_rules() {
        if rule.is_fragment || rule.is_skip() {
            continue;
        }
        let fn_name = format!("tryMatch{}", pascal_case(&rule.name));
        w.line(&format!("const {} = this.{}();", camel_case(&rule.name), fn_name));
        w.line(&format!("if ({}) {{", camel_case(&rule.name)));
        w.indent();
        if rule.is_skip() {
            w.line("continue;");
        } else {
            w.line(&format!("tokens.push({}); continue;", camel_case(&rule.name)));
        }
        w.dedent();
        w.line("}");
    }

    for implicit in &pg.implicit_tokens {
        let fn_name = format!("tryMatch{}", implicit);
        w.line(&format!("const {} = this.{}();", camel_case(implicit), fn_name));
        w.line(&format!("if ({}) {{", camel_case(implicit)));
        w.indent();
        w.line(&format!("tokens.push({}); continue;", camel_case(implicit)));
        w.dedent();
        w.line("}");
    }

    w.line("throw new Error(`Unexpected character '${this.input[this.pos]}' at line ${this.line} col ${this.col}`);");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("tokens.push({{ kind: {}TokenKind.Eof, text: '', line: this.line, col: this.col }});", name));
    w.line("return tokens;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("private advance(): void {");
    w.indent();
    w.line("if (this.pos < this.input.length) {");
    w.indent();
    w.line("if (this.input[this.pos] === '\\n') { this.line++; this.col = 1; }");
    w.line("else { this.col++; }");
    w.line("this.pos++;");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("private peek(offset: number = 0): string | undefined {");
    w.indent();
    w.line("return this.input[this.pos + offset];");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in pg.lexer_rules() {
        if rule.is_fragment {
            continue;
        }
        gen_lexer_match_fn(w, name, rule);
    }

    for implicit in &pg.implicit_tokens {
        gen_implicit_match_fn(w, name, implicit);
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_lexer_match_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("tryMatch{}", pascal_case(&rule.name));
    w.line(&format!("private {}(): {}Token | null {{", fn_name, name));
    w.indent();
    w.line("const savedPos = this.pos;");
    w.line("const savedLine = this.line;");
    w.line("const savedCol = this.col;");

    if rule.alternatives.len() == 1 && rule.alternatives[0].elements.len() == 1 {
        match &rule.alternatives[0].elements[0].kind {
            ElementKind::StringLiteral(lit) => {
                let escaped = escape_string(lit);
                w.line(&format!("const target = \"{}\";", escaped));
                w.line("for (let i = 0; i < target.length; i++) {");
                w.indent();
                w.line("if (this.peek(i) !== target[i]) { this.pos = savedPos; return null; }");
                w.dedent();
                w.line("}");
                w.line("const text = this.input.substring(savedPos, savedPos + target.length);");
                w.line("for (let i = 0; i < target.length; i++) { this.advance(); }");
            }
            ElementKind::CharSet(_cs) => {
                w.line("const start = this.pos;");
                w.line("while (this.pos < this.input.length && this.charInRange(this.input[this.pos])) {");
                w.indent();
                w.line("this.advance();");
                w.dedent();
                w.line("}");
                w.line("if (this.pos === start) { return null; }");
                w.line("const text = this.input.substring(start, this.pos);");
            }
            ElementKind::OneOrMore(block) => {
                if let Some(alt) = block.alternatives.first() {
                    if let Some(elem) = alt.elements.first() {
                        match &elem.kind {
                            ElementKind::CharSet(_) => {
                                w.line("const start = this.pos;");
                                w.line("while (this.pos < this.input.length && this.charInRange(this.input[this.pos])) {");
                                w.indent();
                                w.line("this.advance();");
                                w.dedent();
                                w.line("}");
                                w.line("if (this.pos === start) { return null; }");
                                w.line("const text = this.input.substring(start, this.pos);");
                            }
                            _ => {
                                w.line("const text = '';");
                            }
                        }
                    }
                }
            }
            _ => {
                w.line("const text = this.input.substring(savedPos, this.pos);");
            }
        }
    } else {
        w.line("const text = this.input.substring(savedPos, this.pos);");
    }

    w.blank();
    if rule.is_skip() {
        w.line("return null as any; // skip");
    } else {
        w.line(&format!("return {{ kind: {}TokenKind.{}, text, line: savedLine, col: savedCol }};", name, rule.name));
    }
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_implicit_match_fn(w: &mut super::CodeWriter, name: &str, token_name: &str) {
    let fn_name = format!("tryMatch{}", token_name);
    let lit = token_name_to_literal_ts(token_name);
    let escaped = escape_string(&lit);

    w.line(&format!("private {}(): {}Token | null {{", fn_name, name));
    w.indent();
    w.line("const savedPos = this.pos;");
    w.line("const savedLine = this.line;");
    w.line("const savedCol = this.col;");
    w.line(&format!("const target = \"{}\";", escaped));
    w.line("for (let i = 0; i < target.length; i++) {");
    w.indent();
    w.line("if (this.peek(i) !== target[i]) { return null; }");
    w.dedent();
    w.line("}");
    w.line("const text = this.input.substring(savedPos, savedPos + target.length);");
    w.line("for (let i = 0; i < target.length; i++) { this.advance(); }");
    w.line(&format!("return {{ kind: {}TokenKind.{}, text, line: savedLine, col: savedCol }};", name, token_name));
    w.dedent();
    w.line("}");
    w.blank();
}

fn token_name_to_literal_ts(name: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = name.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if i > 0 && chars[i].is_ascii_uppercase() {
            result.push(chars[i].to_ascii_lowercase());
        } else {
            result.push(chars[i].to_ascii_lowercase());
        }
        i += 1;
    }
    result
}

fn gen_node(w: &mut super::CodeWriter, name: &str, _pg: &ProcessedGrammar) {
    w.line(&format!("export interface {}Node {{", name));
    w.indent();
    w.line("kind: string;");
    w.line(&format!("children: {}Node[];", name));
    w.line("text?: string;");
    w.line(&format!("tokenKind?: {}TokenKind;", name));
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("export function create{}Node(kind: string): {}Node {{", name, name));
    w.indent();
    w.line("return { kind, children: [] };");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("export function createTokenNode(text: string, kind: {}TokenKind): {}Node {{", name, name));
    w.indent();
    w.line("return { kind: 'Token', children: [], text, tokenKind: kind };");
    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser(w: &mut super::CodeWriter, name: &str, pg: &ProcessedGrammar) {
    w.line(&format!("export class {}Parser {{", name));
    w.indent();
    w.line(&format!("private tokens: {}Token[];", name));
    w.line("private pos: number;");
    w.blank();

    w.line(&format!("constructor(tokens: {}Token[]) {{", name));
    w.indent();
    w.line("this.tokens = tokens;");
    w.line("this.pos = 0;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("parse(): {}Node {{", name));
    w.indent();
    let all_parser_rules: Vec<&Rule> = pg.transformed_rules.iter().chain(
        pg.grammar.parser_rules().into_iter().filter(|r| !pg.transformed_rules.iter().any(|tr| tr.name == r.name))
    ).collect();
    if let Some(first) = all_parser_rules.first() {
        w.line(&format!("return this.parse{}();", pascal_case(&first.name)));
    } else {
        w.line("throw new Error('No parser rules defined');");
    }
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private current(): {}Token {{", name));
    w.indent();
    w.line("return this.tokens[this.pos] || this.tokens[this.tokens.length - 1];");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private matchToken(kind: {}TokenKind): {}Token | null {{", name, name));
    w.indent();
    w.line("if (this.current().kind === kind) {");
    w.indent();
    w.line("return this.tokens[this.pos++];");
    w.dedent();
    w.line("}");
    w.line("return null;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("private expect(kind: {}TokenKind): {}Token {{", name, name));
    w.indent();
    w.line(&format!("const tok = this.matchToken(kind);"));
    w.line("if (!tok) {");
    w.indent();
    w.line(&format!("const cur = this.current();"));
    w.line("throw new Error(`Unexpected token ${cur.kind} ('${cur.text}') at line ${cur.line} col ${cur.col}`);");
    w.dedent();
    w.line("}");
    w.line("return tok;");
    w.dedent();
    w.line("}");
    w.blank();

    for rule in &all_parser_rules {
        gen_parser_rule_fn(w, name, rule);
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parser_rule_fn(w: &mut super::CodeWriter, name: &str, rule: &Rule) {
    let fn_name = format!("parse{}", pascal_case(&rule.name));
    w.line(&format!("private {}(): {}Node {{", fn_name, name));
    w.indent();
    w.line(&format!("const node = create{}Node(\"{}\");", name, rule.name));

    if rule.alternatives.len() == 1 {
        gen_parse_elements(w, name, &rule.alternatives[0].elements);
        w.line("return node;");
    } else {
        w.line("switch (this.current().kind) {");
        w.indent();
        for (i, alt) in rule.alternatives.iter().enumerate() {
            let first_elem = alt.elements.first();
            let match_arm = if let Some(elem) = first_elem {
                match &elem.kind {
                    ElementKind::TokenRef(tok) => format!("case {}TokenKind.{}:", name, tok),
                    ElementKind::StringLiteral(lit) => {
                        let tok_name = string_literal_to_token_name(lit);
                        format!("case {}TokenKind.{}:", name, tok_name)
                    }
                    _ => "default:".to_string(),
                }
            } else {
                "default:".to_string()
            };

            if i == rule.alternatives.len() - 1 && match_arm != "default:" {
                w.line("default:");
            } else {
                w.line(&match_arm);
            }
            w.indent();
            gen_parse_elements(w, name, &alt.elements);
            w.line("return node;");
            w.dedent();
        }
        if !rule.alternatives.iter().any(|a| a.elements.is_empty()) {
            w.line("default:");
            w.indent();
            w.line("const cur = this.current();");
            w.line("throw new Error(`Unexpected token ${cur.kind} at line ${cur.line}`);");
            w.dedent();
        }
        w.dedent();
        w.line("}");
    }

    w.dedent();
    w.line("}");
    w.blank();
}

fn gen_parse_elements(w: &mut super::CodeWriter, name: &str, elements: &[Element]) {
    for elem in elements {
        match &elem.kind {
            ElementKind::TokenRef(tok) => {
                w.line(&format!("node.children.push(createTokenNode(this.expect({}TokenKind.{}).text, {}TokenKind.{}));", name, tok, name, tok));
            }
            ElementKind::StringLiteral(lit) => {
                let tok_name = string_literal_to_token_name(lit);
                w.line(&format!("node.children.push(createTokenNode(this.expect({}TokenKind.{}).text, {}TokenKind.{}));", name, tok_name, name, tok_name));
            }
            ElementKind::RuleRef(r) => {
                w.line(&format!("node.children.push(this.parse{}());", pascal_case(r)));
            }
            ElementKind::Optional(block) => {
                w.line("{");
                w.indent();
                w.line("const saved = this.pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (this.pos === saved) { /* optional matched nothing */ }");
                w.dedent();
                w.line("}");
            }
            ElementKind::ZeroOrMore(block) => {
                w.line("while (true) {");
                w.indent();
                w.line("const saved = this.pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (this.pos === saved) { break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::OneOrMore(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("while (true) {");
                w.indent();
                w.line("const saved = this.pos;");
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
                w.line("if (this.pos === saved) { break; }");
                w.dedent();
                w.line("}");
            }
            ElementKind::Group(block) => {
                for alt in &block.alternatives {
                    gen_parse_elements(w, name, &alt.elements);
                }
            }
            _ => {}
        }
    }
}
